scripts/setup.py
- name: Lint Python and JS files
  run: |
    echo "Linting Python..."
    flake8 scripts/ || true  # or use black, pylint, etc.
    echo "Linting JS..."
    npx eslint . || true
    - name: Run Unit Tests (Python and JS)
  run: |
    echo "Running Python tests..."
    pytest tests/ || true
    echo "Running JavaScript tests..."
    npm test || true
- name: Deploy to n8n via API
  env:
    N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
  run: |
    curl -X POST https://n8n.yourdomain.com/api/workflows/your-workflow-id/activate \
    -H "Authorization: Bearer $N8N_API_KEY"


    
